In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\italo\.conda\envs\dataeco\lib\site-packages (1.4.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pandas) (1.23.2)
Requirement already satisfied: six>=1.5 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [7]:
teste = pd.read_csv('C:/Users/italo/.Data Science/Macro_Py/estudo.csv',encoding='latin-1')

In [10]:
teste

,Unnamed: 0,X,id,menina,branco,cidade_id,escola_id,prof_id,name_muni,pib,prof_nome,prof_exp,inf,trtGrp,sala_pequena,sala_professor_integral,nota
0,1,1,1,1,1,16,Tamboril Do Piauí_4,62,Tamboril Do Piauí,4790.742326,Osnilda das Neves,6.338631,4.625265,2,1,0,92.083018
1,2,2,2,0,1,8,Dom Inocêncio_1,120,Dom Inocêncio,4110.471929,Verdi da Cunha,13.436436,2.986223,1,0,0,56.567140
2,3,3,3,1,1,6,Coronel José Dias_4,110,Coronel José Dias,3999.824452,Aldo Araújo,7.999814,3.729349,2,1,0,70.419100
3,4,4,4,1,1,6,Coronel José Dias_3,108,Coronel José Dias,3999.824452,Uirá de Souza,20.673742,6.845187,1,0,0,53.353603
4,5,5,5,1,1,1,Anísio De Abreu_3,6,Anísio De Abreu,3732.898597,Ferrer Farias,12.934466,2.168085,2,1,0,84.262781
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1132,1133,1133,1133,1,0,11,Jurema_2,19,Jurema,2736.025219,Josiane Sales,14.668063,3.449933,2,1,0,52.413702
1133,1134,1134,1134,0,1,9,Fartura Do Piauí_2,131,Fartura Do Piauí,4776.252907,Marinei Fogaça,15.960212,3.056001,1,0,0,39.404632
1134,1135,1135,1135,1,1,3,Brejo Do Piauí_1,80,Brejo Do Piauí,3422.315868,Alberta Lopes,20.556315,3.388773,3,0,1,46.202198
1135,1136,1136,1136,1,0,15,São Raimundo Nonato_3,54,São Raimundo Nonato,5793.132515,Eufrásio Ribeiro,22.409759,7.355818,1,0,0,56.123213
1136,1137,1137,1137,1,1,4,Canto Do Buriti_2,90,Canto Do Buriti,4236.559793,Eusébio Almeida,15.364945,8.480474,3,0,1,67.918226