# Python para economistas

### Importação de dados

Nesta aula mostraremos como importar dados de diferentes fontes e formatos no Python. Esta lista não é exaustiva. Assim, se você precisar importar para o Python algum arquivo com formato diferente dos citados, é quase certo que há uma maneira de fazer isso.

### API

É o caminho mais natural e automatizável de fazer a importação de dados no Python. Para isso, basta instalar a biblioteca que traz a interface junto a API que você deseja extrair os dados e utilizar as funções específicas do pacote. Cada biblioteca vai ter funções específicas, ou seja, é preciso ler a documentação da biblioteca em questão. Para procurar pacotes e suas documentações, acesse https://pypi.org/.

Para mostrar um exemplo, iremos mostrar o uso da biblioteca "sidrapy", que permite acesso ao API do SIDRA-IBGE. É preciso saber o número da tabela do sidra que desejamos extrair, no caso a 1419, que mostra os dados de inflação. Veja que há outros argumentos na função que servem como filtros dos dados.

In [33]:
pip install -U sidrapy

Requirement already satisfied: sidrapy in c:\users\italo\.conda\envs\dataeco\lib\site-packages (0.1.3)
Requirement already satisfied: requests in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from sidrapy) (2.27.1)
Requirement already satisfied: pandas in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from sidrapy) (1.4.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pandas->sidrapy) (1.23.2)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pandas->sidrapy) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pandas->sidrapy) (2022.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from requests->sidrapy) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from requests->sidrapy) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from requests->sidrapy) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from requests->sidrapy) (2022.6.15)
Requirement already satisfied: six>=1.5 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from python-dateutil>=2.8.1->pandas->sidrapy) (1.12.0)
Note: you may need to restart the kernel to use updated packages.

In [34]:
##ACESSO API SIDRA-IBGE

import sidrapy

data = sidrapy.get_table(table_code="1419", territorial_level="1", 
                         ibge_territorial_code="all", period="last 12")

data.head()

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
0,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Brasil (Código),Brasil,Mês (Código),Mês,Variável (Código),Variável,"Geral, grupo, subgrupo, item e subitem (Código)","Geral, grupo, subgrupo, item e subitem"
1,1,Brasil,2,%,0.32,1,Brasil,201901,janeiro 2019,63,IPCA - Variação mensal,7169,Índice geral
2,1,Brasil,2,%,0.32,1,Brasil,201901,janeiro 2019,69,IPCA - Variação acumulada no ano,7169,Índice geral
3,1,Brasil,2,%,3.78,1,Brasil,201901,janeiro 2019,2265,IPCA - Variação acumulada em 12 meses,7169,Índice geral
4,1,Brasil,2,%,100.0000,1,Brasil,201901,janeiro 2019,66,IPCA - Peso mensal,7169,Índice geral

### Excel

Para importar arquivos de excel, iremos utilizar a biblioteca Pandas. Assim, a função "read_excel" importa no formato dataframe. Além do Pandas, é necessário instalar a biblioteca "openpyxl".

Como o arquivo que estamos utilizando está dentro da pasta do projeto, é apenas necessário colocar o nome do arquivo e o formato. Caso contrário, seria necessário indicar o caminho dele dentro de seu computador (ex: "./arquivos/excel/iris.xlsx")

In [32]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\italo\.conda\envs\dataeco\lib\site-packages (3.0.10)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: et-xmlfile in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from openpyxl) (1.1.0)

In [30]:
pip install pandas

Requirement already satisfied: pandas in c:\users\italo\.conda\envs\dataeco\lib\site-packages (1.4.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pandas) (1.23.2)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: six>=1.5 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.12.0)
Note: you may need to restart the kernel to use updated packages.

In [29]:
import pandas as pd

iris_excel = pd.read_excel('iris.xlsx')
iris_excel

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

### CSV

Importar arquivos no formato CSV é semelhante ao que fizemos com arquivos de excel.

In [28]:
import pandas as pd

iris_csv = pd.read_csv('iris.csv')  
iris_csv

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

### Stata

Para importar dados do Stata (formato dta) é preciso utilizar a biblioteca "pyreadstat". A função retorna duas partes do arquivo: os dados e os metadados, que são informações sobre a base. Assim, é preciso colocar os resultados da função em dois objetos diferentes, o que é feito separando os arquivos do lado esquerdo por uma virgula.

In [27]:
pip install pyreadstat

Requirement already satisfied: pyreadstat in c:\users\italo\.conda\envs\dataeco\lib\site-packages (1.1.9)
Requirement already satisfied: pandas>=1.2.0 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pyreadstat) (1.4.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2022.1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pandas>=1.2.0->pyreadstat) (1.23.2)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from python-dateutil>=2.8.1->pandas>=1.2.0->pyreadstat) (1.12.0)
Note: you may need to restart the kernel to use updated packages.

In [26]:
import pyreadstat

olympics, meta = pyreadstat.read_dta('olympics.dta')

In [25]:
olympics.head()

,country,year,gdp,pop,gold,silver,bronze,medaltot,host,planned,soviet
0,1.0,80.0,2.660000e+10,16000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,84.0,2.990000e+10,17600000.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
2,2.0,80.0,2.450000e+09,2671000.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0
3,2.0,84.0,2.660000e+09,2897000.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0
4,2.0,88.0,2.800000e+09,3138000.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0

In [24]:
meta.notes

['Andrew B. Bernard and Meghan R. Busse "Who wins the olympic games: Economic resources and medal totals," The Review of Economics and Statistics, February 2004, 86(1), 413-417.',
 '1']

### PDF

Muitas vezes pode ser interessante, ou necessário, extrair informações de arquivos PDF. Colocamos dois exemplos diferentes desse tipo de caso. No primeiro, estamos interessados em extrair o texto do pdf, para fazer uma análise de sentimentos, por exemplo. No segundo, os dados estão tabulados no formato PDF. 

Para o primeiro caso, utilizamos a biblioteca "textract", que fornece um procedimento bastante simples. Já no segundo caso, utilizamos a biblioteca "tabula-py", que trabalha com algoritmos que permitem identificar a formatação da tabela e a transformação destes dados em um dataframe comum. Como no nosso exemplo, temos várias tabelas diferentes espalhadas pelo pdf, a função retorna uma lista. Assim, para acessar uma tabela em específico, tudo que precisamos fazer é acessar o elemento desta tabela na lista.

In [63]:
pip install textract

Requirement already satisfied: textract in c:\users\italo\.conda\envs\dataeco\lib\site-packages (1.6.5)
Requirement already satisfied: extract-msg<=0.29.* in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from textract) (0.28.7)
Requirement already satisfied: chardet==3.* in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from textract) (3.0.4)
Requirement already satisfied: six~=1.12.0 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from textract) (1.12.0)
Requirement already satisfied: docx2txt~=0.8 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from textract) (0.8)
Requirement already satisfied: beautifulsoup4~=4.8.0 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from textract) (4.8.2)
Requirement already satisfied: SpeechRecognition~=3.8.1 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from textract) (3.8.1)
Requirement already satisfied: argcomplete~=1.10.0 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from textract) (1.10.3)
Requirement already satisfied: xlrd~=1.2.0 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from textract) (1.2.0)
Requirement already satisfied: pdfminer.six==20191110 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from textract) (20191110)
Requirement already satisfied: python-pptx~=0.6.18 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from textract) (0.6.21)
Requirement already satisfied: sortedcontainers in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pdfminer.six==20191110->textract) (2.4.0)
Requirement already satisfied: pycryptodome in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pdfminer.six==20191110->textract) (3.15.0)
Requirement already satisfied: soupsieve>=1.2 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from beautifulsoup4~=4.8.0->textract) (2.3.2.post1)
Requirement already satisfied: tzlocal>=2.1 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from extract-msg<=0.29.*->textract) (4.2)
Requirement already satisfied: olefile>=0.46 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from extract-msg<=0.29.*->textract) (0.46)
Requirement already satisfied: ebcdic>=1.1.1 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from extract-msg<=0.29.*->textract) (1.1.1)
Requirement already satisfied: compressed-rtf>=1.0.6 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from extract-msg<=0.29.*->textract) (1.0.6)
Requirement already satisfied: imapclient==2.1.0 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from extract-msg<=0.29.*->textract) (2.1.0)
Requirement already satisfied: Pillow>=3.3.2 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from python-pptx~=0.6.18->textract) (9.2.0)
Requirement already satisfied: XlsxWriter>=0.5.7 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from python-pptx~=0.6.18->textract) (3.0.3)
Requirement already satisfied: lxml>=3.1.0 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from python-pptx~=0.6.18->textract) (4.9.1)
Requirement already satisfied: pytz-deprecation-shim in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from tzlocal>=2.1->extract-msg<=0.29.*->textract) (0.1.0.post0)
Requirement already satisfied: tzdata in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from tzlocal>=2.1->extract-msg<=0.29.*->textract) (2022.2)
Note: you may need to restart the kernel to use updated packages.

In [71]:
import textract

text = textract.process("exemplo.pdf")
text

ShellError: The command `pdftotext exemplo.pdf -` failed with exit code 127
------------- stdout -------------
------------- stderr -------------

In [68]:
pip install tabula-py

Collecting tabula-pyNote: you may need to restart the kernel to use updated packages.
  Downloading tabula_py-2.5.0-py3-none-any.whl (12.0 MB)
     ---------------------------------------- 12.0/12.0 MB 9.2 MB/s eta 0:00:00
Collecting distro
  Downloading distro-1.7.0-py3-none-any.whl (20 kB)
Requirement already satisfied: numpy in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from tabula-py) (1.23.2)
Requirement already satisfied: pandas>=0.25.3 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from tabula-py) (1.4.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pandas>=0.25.3->tabula-py) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\italo\.conda\envs\dataeco\lib\site-packages (from python-dateutil>=2.8.1->pandas>=0.25.3->tabula-py) (1.12.0)
Installing collected packages: distro, tabula-py
Successfully installed distro-1.7.0 tabula-py-2.5.0

In [70]:
import tabula

# Read pdf into list of DataFrame
lista = tabula.read_pdf("exemplo_tabela.pdf", pages='all', 
                        multiple_tables=True,silent=True)

lista[0]

     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5